using System.Text;

namespace Genbox.EnumSourceGen.Generators;

internal static class EnumFormatCode
{
    internal static string Generate(EnumSpec es, AttributeOptions op, StringBuilder sb)
    {
        string? ns = op.EnumsClassNamespace ?? es.Namespace;
        string cn = op.EnumNameOverride ?? es.Name;

        string res = $$"""
// <auto-generated />
{{(ns != null ? "\nnamespace " + ns + ";\n" : null)}}
[Flags]
public enum {{cn}}Format : byte
{
    None = 0,
    Name = 1,
    Value = 2,
""";

        if (es.HasDisplay)
        {
            res += """

    DisplayName = 4,
""";
        }

        if (es.HasDescription)
        {
            res += """

    Description = 8,
""";
        }

        res += """

    Default = Name | Value
}
""";
        return res;
    }
}