using System.Text;
using Genbox.EnumSourceGen.Helpers;

namespace Genbox.EnumSourceGen.Generators;

internal static class EnumExtensionCode
{
    public static string Generate(EnumSpec es, AttributeOptions op, StringBuilder sb)
    {
        sb.Clear();

        string? ns = op.ExtensionsNamespace ?? es.Namespace;
        string cn = op.EnumNameOverride ?? es.Name;
        string en = op.ExtensionsName ?? cn + "Extensions";
        string sn = es.FullyQualifiedName;
        string vi = es.IsPublic ? "public" : "internal";
        string ut = es.UnderlyingType;

        string res = $$"""
// <auto-generated />
#nullable enable
using System.Diagnostics.CodeAnalysis;
{{(ns != null ? "\nnamespace " + ns + ";\n" : null)}}
{{vi}} static partial class {{en}}
{
    public static string GetString(this {{sn}} value)
        => value switch
        {
            {{GetString()}}
            _ => value.ToString()
        };

    public static bool TryGetUnderlyingValue(this {{sn}} value, out {{ut}} underlyingValue)
    {
        switch (value)
        {
{{TryGetUnderlyingValue()}}
        }
        underlyingValue = default;
        return false;
    }

    public static {{ut}} GetUnderlyingValue(this {{sn}} value)
    {
        if (!TryGetUnderlyingValue(value, out {{ut}} underlyingValue))
            throw new ArgumentOutOfRangeException($"Invalid value: {value}");

        return underlyingValue;
    }
""";

        if (es.HasDisplay)
        {
            res += $$"""


    public static bool TryGetDisplayName(this {{sn}} value, [NotNullWhen(true)]out string? displayName)
    {
        switch (value)
        {
{{TryGetDisplayName()}}
        }
        displayName = null;
        return false;
    }

    public static string GetDisplayName(this {{sn}} value)
    {
        if (!TryGetDisplayName(value, out string? displayName))
            throw new ArgumentOutOfRangeException($"Invalid value: {value}");

        return displayName;
    }
""";
        }

        if (es.HasDescription)
        {
            res += $$"""


    public static bool TryGetDescription(this {{sn}} value, [NotNullWhen(true)]out string? description)
    {
        switch (value)
        {
{{TryGetDescription()}}
        }
        description = null;
        return false;
    }

    public static string GetDescription(this {{sn}} value)
    {
        if (!TryGetDescription(value, out string? description))
            throw new ArgumentOutOfRangeException($"Invalid value: {value}");

        return description;
    }
""";
        }

        if (es.HasFlags)
        {
            res += $$"""


    public static bool IsFlagSet(this {{sn}} value, {{sn}} flag)
        => (({{ut}})value & ({{ut}})flag) == ({{ut}})flag;
""";
        }

        string GetString()
        {
            sb.Clear();

            for (int i = 0; i < es.Members.Count; i++)
            {
                EnumMember enumMember = es.Members[i];

                if (enumMember.Omit && !enumMember.OmitFiler.HasFlag(EnumOmitExclude.GetString))
                {
                    sb.Append(sn).Append('.').Append(enumMember.Name).Append(" => string.Empty,\n            ");
                    continue;
                }

                string transformed = TransformHelper.TransformName(enumMember);

                sb.Append(sn).Append('.').Append(enumMember.Name).Append(" => \"").Append(transformed).Append("\",\n            ");
            }

            return sb.ToString().TrimEnd();
        }

        string TryGetUnderlyingValue()
        {
            sb.Clear();

            for (int i = 0; i < es.Members.Count; i++)
            {
                EnumMember enumMember = es.Members[i];

                if (enumMember.Omit && !enumMember.OmitFiler.HasFlag(EnumOmitExclude.GetUnderlyingValue))
                    continue;

                sb.Append($$"""
            case {{sn}}.{{enumMember.Name}}:
                underlyingValue = {{enumMember.Value}};
                return true;
""");

                if (i != es.Members.Count - 1)
                    sb.AppendLine();
            }

            return sb.ToString();
        }

        string TryGetDisplayName()
        {
            sb.Clear();

            for (int i = 0; i < es.Members.Count; i++)
            {
                EnumMember enumMember = es.Members[i];

                if (enumMember.Omit && !enumMember.OmitFiler.HasFlag(EnumOmitExclude.GetDisplayName))
                    continue;

                if (enumMember.DisplayName == null)
                    continue;

                sb.Append($$"""
            case {{sn}}.{{enumMember.Name}}:
                displayName = "{{enumMember.DisplayName}}";
                return true;
""");

                if (i != es.Members.Count - 1)
                    sb.AppendLine();
            }

            return sb.ToString();
        }

        string TryGetDescription()
        {
            sb.Clear();

            for (int i = 0; i < es.Members.Count; i++)
            {
                EnumMember enumMember = es.Members[i];

                if (enumMember.Omit && !enumMember.OmitFiler.HasFlag(EnumOmitExclude.GetDescription))
                    continue;

                if (enumMember.Description == null)
                    continue;

                sb.Append($$"""
            case {{sn}}.{{enumMember.Name}}:
                description = "{{enumMember.Description}}";
                return true;
""");

                if (i != es.Members.Count - 1)
                    sb.AppendLine();
            }

            return sb.ToString();
        }

        return res + "\n}";
    }
}