name: Generic build

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

env:
  DOTNET_EnableDiagnostics: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core 9.0
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.0.x'
      - name: Build
        shell: pwsh
        run: |
          ./Scripts/Build.ps1