using System.Collections.Immutable;
using Genbox.FastEnum.Generators;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Genbox.FastEnum;

/// <summary>Generates optimized helper APIs for enums marked with <see cref="FastEnumAttribute" />.</summary>
[Generator(LanguageNames.CSharp)]
public class EnumGenerator : IIncrementalGenerator
{
    private const string DisplayAttribute = "System.ComponentModel.DataAnnotations.DisplayAttribute";
    private const string FlagsAttribute = "System.FlagsAttribute";
    private const string FastEnumAttr = $"Genbox.FastEnum.{nameof(FastEnumAttribute)}";
    private const string EnumTransformAttr = $"Genbox.FastEnum.{nameof(EnumTransformAttribute)}";
    private const string EnumTransformValueAttr = $"Genbox.FastEnum.{nameof(EnumTransformValueAttribute)}";
    private const string EnumOmitValueAttr = $"Genbox.FastEnum.{nameof(EnumOmitValueAttribute)}";
    private const string Header = """
                                  // <auto-generated />
                                  #nullable enable
                                  """;
    internal static string GeneratedCodeAttribute { get; } = $"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"FastEnum\", \"{typeof(EnumGenerator).Assembly.GetName().Version}\")]";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<EnumSpec>> collectedEnums = context.SyntaxProvider
                                                                                   .ForAttributeWithMetadataName(FastEnumAttr, static (node, _) => node is EnumDeclarationSyntax declaration && declaration.AttributeLists.Count > 0, Transform)
                                                                                   .Where(spec => spec != null)
                                                                                   .WithTrackingName("EnumSpecs")
                                                                                   .Collect()
                                                                                   .WithTrackingName("CollectedEnums")!;

        IncrementalValueProvider<GenerationPlan> plan = collectedEnums.Select(static (specs, _) => CreatePlan(specs));
        context.RegisterSourceOutput(plan.Select(static (value, _) => value.Error), static (spc, message) =>
        {
            if (message != null)
            {
                DiagnosticDescriptor report = new DiagnosticDescriptor("FE001", "FastEnum", $"Validation failed with message: {message}", "errors", DiagnosticSeverity.Error, true);
                spc.ReportDiagnostic(Diagnostic.Create(report, Location.None));
            }
        });

        // Structural equality stops unchanged inputs before the expensive source emission callback.
        IncrementalValuesProvider<GenerationInput> inputs = plan.SelectMany(static (value, _) => value.Inputs)
                                                                .WithTrackingName("GenerationInputs");
        context.RegisterSourceOutput(inputs, EmitSources);
    }

    private static void EmitSources(SourceProductionContext context, GenerationInput input)
    {
        if (context.CancellationToken.IsCancellationRequested)
            return;

        EnumSpec spec = input.Spec;

        try
        {
            context.AddSource($"{spec.FullName}_EnumFormat.g.cs", GetSource(Header, spec, EnumFormatCode.Generate));
            context.AddSource($"{spec.FullName}_Enums.g.cs", GetSource(Header, spec, enumSpec => EnumClassCode.Generate(enumSpec, input.IsWrapperPublic, input.IncludeWrapperAttribute)));
            context.AddSource($"{spec.FullName}_Extensions.g.cs", GetSource(Header, spec, enumSpec => EnumExtensionCode.Generate(enumSpec, input.IncludeExtensionAttribute)));
        }
        catch (Exception exception)
        {
            DiagnosticDescriptor report = new DiagnosticDescriptor("ESG002", "FastEnum", $"An error happened while generating code for {spec.FullName}. Error: {exception.Message}", "errors", DiagnosticSeverity.Error, true);
            context.ReportDiagnostic(Diagnostic.Create(report, Location.None));
        }
    }

    private static GenerationPlan CreatePlan(ImmutableArray<EnumSpec> specs)
    {
        if (!IsSpecsValid(specs, out string? message))
            return new GenerationPlan(message, ImmutableArray<GenerationInput>.Empty);

        // Every declaration of a shared partial wrapper must use the same visibility.
        HashSet<string> publicWrappers = new HashSet<string>(StringComparer.Ordinal);

        foreach (EnumSpec spec in specs)
        {
            FastEnumData data = spec.Data;
            bool isPublic = data.EnumsClassVisibility == Visibility.Public || (data.EnumsClassVisibility == Visibility.Inherit && spec.IsPubliclyAccessible);

            if (!data.DisableEnumsWrapper && isPublic)
                publicWrappers.Add(JoinName(data.EnumsClassNamespace ?? spec.Namespace, data.EnumsClassName ?? "Enums"));
        }

        // Apply GeneratedCodeAttribute only to the first declaration of each shared type.
        HashSet<string> attributedTypes = new HashSet<string>(StringComparer.Ordinal);
        ImmutableArray<GenerationInput>.Builder inputs = ImmutableArray.CreateBuilder<GenerationInput>(specs.Length);

        foreach (EnumSpec spec in specs)
        {
            FastEnumData data = spec.Data;
            string wrapperName = JoinName(data.EnumsClassNamespace ?? spec.Namespace, data.EnumsClassName ?? "Enums");
            string extensionName = JoinName(data.ExtensionClassNamespace ?? spec.Namespace, data.ExtensionClassName ?? $"{spec.Name}Extensions");
            bool hasWrapper = !data.DisableEnumsWrapper;
            bool isWrapperPublic = hasWrapper && publicWrappers.Contains(wrapperName);
            bool includeWrapperAttribute = hasWrapper && attributedTypes.Add(wrapperName);
            bool includeExtensionAttribute = attributedTypes.Add(extensionName);

            inputs.Add(new GenerationInput(spec, isWrapperPublic, includeWrapperAttribute, includeExtensionAttribute));
        }

        return new GenerationPlan(null, inputs.MoveToImmutable());
    }

    private static bool IsSpecsValid(ImmutableArray<EnumSpec> specs, out string? message)
    {
        foreach (EnumSpec es in specs)
        {
            if (es.HasFileLocalType)
                return Fail($"FastEnum is not supported on file-local enum '{es.FullName}' or an enum inside a file-local containing type", out message);

            if (es.HasGenericContainingType)
                return Fail($"FastEnum is not supported on enum '{es.FullName}' inside a generic containing type", out message);
        }

        if (!AreGeneratedNamesValid(specs, out message))
            return false;

        return AreVisibilitiesValid(specs, out message);
    }

    private static bool AreGeneratedNamesValid(ImmutableArray<EnumSpec> specs, out string? message)
    {
        // By default, the enum helper is generated as <enum_namespace>.<enums_class_name>.<enum_name>.
        // <enum_namespace> is the namespace of the user's enum. It can be overridden by EnumsClassNamespace.
        // <enums_class_name> defaults to "Enums". It can be overridden by EnumsClassName.
        // <enum_name> is the name of the user's enum. It can be overridden by EnumNameOverride.
        //
        // The format enum and extension class also derive their names from these inputs. Combine the semantic names
        // of every generated type and check for duplicates so escaped identifiers cannot hide a collision.
        Dictionary<string, string> emittedTypes = new Dictionary<string, string>(StringComparer.Ordinal); // Case-sensitive since C# is too.
        Dictionary<string, bool> extensionVisibilities = new Dictionary<string, bool>(StringComparer.Ordinal);

        foreach (EnumSpec es in specs)
        {
            FastEnumData esd = es.Data;

            // Validate user-provided identifiers before they are emitted into generated C#.
            if (!IsValidIdentifierOverride(esd.EnumNameOverride, nameof(FastEnumAttribute.EnumNameOverride), out message) ||
                !IsValidIdentifierOverride(esd.EnumsClassName, nameof(FastEnumAttribute.EnumsClassName), out message) ||
                !IsValidIdentifierOverride(esd.ExtensionClassName, nameof(FastEnumAttribute.ExtensionClassName), out message))
                return false;

            // Namespace overrides are also code, so reject invalid qualified names early.
            if (!IsValidNamespaceOverride(esd.EnumsClassNamespace, nameof(FastEnumAttribute.EnumsClassNamespace), out message) ||
                !IsValidNamespaceOverride(esd.ExtensionClassNamespace, nameof(FastEnumAttribute.ExtensionClassNamespace), out message))
                return false;

            string? enumNamespace = esd.EnumsClassNamespace ?? es.Namespace;
            string enumClassName = esd.EnumsClassName ?? "Enums";
            string enumName = es.Name;
            string? extensionNamespace = esd.ExtensionClassNamespace ?? es.Namespace;
            string extensionName = esd.ExtensionClassName ?? $"{enumName}Extensions";
            string extensionFullName = JoinName(extensionNamespace, extensionName);
            bool extensionPublic = esd.ExtensionClassVisibility == Visibility.Public || (esd.ExtensionClassVisibility == Visibility.Inherit && es.IsPubliclyAccessible);

            // Validate every emitted type using semantic identifiers; Foo and @Foo name the same type.
            if ((!esd.DisableEnumsWrapper && !AddEmittedType(JoinName(enumNamespace, enumClassName), "wrapper", true, out message)) ||
                !AddEmittedType(esd.DisableEnumsWrapper ? JoinName(enumNamespace, enumName) : JoinName(enumNamespace, enumClassName, enumName), "enum helper", false, out message) ||
                !AddEmittedType(JoinName(enumNamespace, $"{enumName}Format"), "format enum", false, out message) ||
                !AddEmittedType(extensionFullName, "extension class", true, out message) ||
                !AddExtensionVisibility(extensionFullName, extensionPublic, out message))
                return false;
        }

        message = null;
        return true;

        bool AddEmittedType(string fullName, string kind, bool allowSharedType, out string? error)
        {
            if (!emittedTypes.TryGetValue(fullName, out string? existingKind))
            {
                emittedTypes.Add(fullName, kind);
                error = null;
                return true;
            }

            if (allowSharedType && existingKind == kind)
            {
                error = null;
                return true;
            }

            return Fail($"Generated {kind} collides with generated {existingKind}: {fullName}. Use a FastEnum name or namespace override to resolve the conflict", out error);
        }

        bool AddExtensionVisibility(string fullName, bool isPublic, out string? error)
        {
            if (!extensionVisibilities.TryGetValue(fullName, out bool existingVisibility))
            {
                extensionVisibilities.Add(fullName, isPublic);
                error = null;
                return true;
            }

            if (existingVisibility == isPublic)
            {
                error = null;
                return true;
            }

            return Fail($"Generated extension class has conflicting visibility: {fullName}. Use matching ExtensionClassVisibility values or separate extension classes", out error);
        }
    }

    private static bool AreVisibilitiesValid(ImmutableArray<EnumSpec> specs, out string? message)
    {
        // We don't support private enums. For example:
        //
        // public class MyClass
        // {
        //     private enum MyEnum { Value }
        // }
        //
        // The generated Enums.MyEnum class cannot access the enum because it is private. Disabling the Enums wrapper
        // does not help because the resulting MyEnum class and generated extension methods still cannot access it.
        // Namespace-level helpers can access public, internal, and protected internal enums only when every containing
        // type is also accessible from the same assembly. A public enum inside an internal type is supported, but its
        // inherited helper visibility is internal because the enum's effective accessibility is limited by its container.
        foreach (EnumSpec es in specs)
        {
            //The first part of the AccessChain is the enum's own accessibility
            Accessibility enumAccess = es.AccessChain[0];

            if (enumAccess == Accessibility.Private)
                return Fail($"FastEnum is not supported on private enum: '{es.FullName}'", out message);

            if (enumAccess != Accessibility.Internal && enumAccess != Accessibility.Public && enumAccess != Accessibility.ProtectedOrInternal)
                return Fail($"Unsupported visibility '{enumAccess}' on '{es.FullName}'", out message);

            // Every containing type must be accessible to the generated helpers.
            for (int i = 1; i < es.AccessChain.Length; i++)
            {
                Accessibility parentAccess = es.AccessChain[i];

                if (parentAccess != Accessibility.Public && parentAccess != Accessibility.Internal && parentAccess != Accessibility.ProtectedOrInternal)
                    return Fail($"Containing type visibility ({parentAccess}) prevents generated helpers from accessing enum '{es.FullName}'", out message);
            }

            FastEnumData data = es.Data;

            if (!es.IsPubliclyAccessible && data.EnumsClassVisibility == Visibility.Public)
                return Fail($"Your visibility override ({data.EnumsClassVisibility}) on the enums class must be less or equal to the visibility on the enum '{es.FullName} ({enumAccess})", out message);

            if (!es.IsPubliclyAccessible && data.ExtensionClassVisibility == Visibility.Public)
                return Fail($"Your visibility override ({data.ExtensionClassVisibility}) on the extensions class must be less or equal to the visibility on the enum '{es.FullName} ({enumAccess})", out message);
        }

        message = null;
        return true;
    }

    private static string JoinName(string? @namespace, params string[] names)
    {
        string name = string.Join(".", Array.ConvertAll(names, NormalizeIdentifier));

        return @namespace == null ? name : $"{NormalizeQualifiedName(@namespace)}.{name}";
    }

    private static string NormalizeQualifiedName(string value) => string.Join(".", Array.ConvertAll(value.Split('.'), NormalizeIdentifier));

    private static string NormalizeIdentifier(string value) => value.Length > 0 && value[0] == '@' ? value.Substring(1) : value;

    private static bool IsValidIdentifierOverride(string? value, string propertyName, out string? message) => IsValidOverride(value, propertyName, "identifier", IsValidIdentifier, out message);

    private static bool IsValidNamespaceOverride(string? value, string propertyName, out string? message) => IsValidOverride(value, propertyName, "namespace", IsValidNamespace, out message);

    private static bool IsValidOverride(string? value, string propertyName, string kind, Func<string, bool> isValid, out string? message)
    {
        if (value == null || isValid(value))
        {
            message = null;
            return true;
        }

        return Fail($"Invalid C# {kind} '{value}' in {propertyName}", out message);
    }

    private static bool IsValidNamespace(string value) => Array.TrueForAll(value.Split('.'), IsValidIdentifier);

    private static bool Fail(string error, out string? message)
    {
        message = error;
        return false;
    }

    private static bool IsValidIdentifier(string value)
    {
        if (SyntaxFacts.IsValidIdentifier(value))
            return true;

        // Overrides may retain an explicit escape even when the semantic identifier is ordinary.
        if (value.Length < 2 || value[0] != '@')
            return false;

        string unescaped = value.Substring(1);
        return SyntaxFacts.IsValidIdentifier(unescaped) || SyntaxFacts.GetKeywordKind(unescaped) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(unescaped) != SyntaxKind.None;
    }

    private static SourceText GetSource(string header, EnumSpec spec, Func<EnumSpec, string> generate)
    {
        string source = $"""
                         {header}
                         {generate(spec)}
                         """;
        return SourceText.From(source, Encoding.UTF8);
    }

    private static EnumSpec? Transform(GeneratorAttributeSyntaxContext context, CancellationToken token)
    {
        if (context.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        bool hasFlags = false;
        FastEnumData? fastEnumData = null;
        EnumTransformData? enumTransformData = null;

        foreach (AttributeData ad in symbol.GetAttributes())
        {
            if (ad.AttributeClass == null)
                continue;

            string name = ad.AttributeClass.ToDisplayString();

            if (name.Equals(FastEnumAttr, StringComparison.Ordinal))
                fastEnumData = TypeHelper.MapData<FastEnumData>(ad.NamedArguments);
            else if (name.Equals(FlagsAttribute, StringComparison.Ordinal))
                hasFlags = true;
            else if (name.Equals(EnumTransformAttr, StringComparison.Ordinal))
                enumTransformData = TypeHelper.MapData<EnumTransformData>(ad.NamedArguments);
        }

        if (fastEnumData == null)
            return null;

        //Now we read attributes applied to members of the enum
        ImmutableArray<ISymbol> enumMembers = symbol.GetMembers();
        List<EnumMemberSpec> members = new List<EnumMemberSpec>(enumMembers.Length);

        bool hasName = false;
        bool hasDescription = false;

        foreach (ISymbol member in enumMembers)
        {
            if (member is not IFieldSymbol field || field.ConstantValue == null)
                continue;

            DisplayData? displayData = null;
            EnumTransformValueData? transformValueData = null;
            EnumOmitValueData? omitValueData = null;

            foreach (AttributeData ad in field.GetAttributes())
            {
                if (ad.AttributeClass == null)
                    continue;

                string name = ad.AttributeClass.ToDisplayString();

                if (name.Equals(DisplayAttribute, StringComparison.Ordinal))
                {
                    displayData = TypeHelper.MapData<DisplayData>(ad.NamedArguments);

                    hasName |= displayData.Name != null;
                    hasDescription |= displayData.Description != null;
                }
                else if (name.Equals(EnumTransformValueAttr, StringComparison.Ordinal))
                    transformValueData = TypeHelper.MapData<EnumTransformValueData>(ad.NamedArguments);
                else if (name.Equals(EnumOmitValueAttr, StringComparison.Ordinal))
                {
                    // If no arguments are given, we default to exclude all
                    if (ad.NamedArguments.Length == 0)
                        omitValueData = new EnumOmitValueData { Exclude = EnumOmitExclude.All };
                    else
                        omitValueData = TypeHelper.MapData<EnumOmitValueData>(ad.NamedArguments);
                }
            }

            string memberName = member.Name;
            members.Add(new EnumMemberSpec(memberName, EscapeIdentifier(memberName), field.ConstantValue, displayData, omitValueData, transformValueData));
        }

        // Underlying framework type names must not bind to user-defined symbols.
        string underlyingType = symbol.EnumUnderlyingType?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ?? "global::System.Int32";

        List<Accessibility> accessChain = new List<Accessibility>();

        INamedTypeSymbol? curSym = symbol;
        bool hasFileLocalType = false;

        while (curSym != null)
        {
            hasFileLocalType |= curSym.IsFileLocal;
            accessChain.Add(curSym.DeclaredAccessibility);
            curSym = curSym.ContainingType;
        }

        string enumName = NormalizeIdentifier(fastEnumData.EnumNameOverride ?? symbol.Name);

        // Symbol display formats handle containing types; only code references retain escapes and the global qualifier.
        string enumFullName = symbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat).Replace("@", "");
        string fqn = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        string? enumNamespace = symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString();
        bool hasGenericContainingType = false;

        for (INamedTypeSymbol? containingType = symbol.ContainingType; containingType != null; containingType = containingType.ContainingType)
            hasGenericContainingType |= containingType.Arity > 0;

        return new EnumSpec(enumName, EscapeIdentifier(enumName), enumFullName, fqn, enumNamespace, accessChain.ToArray(), hasGenericContainingType, hasName, hasDescription, hasFlags, underlyingType, fastEnumData, members.ToArray(), enumTransformData, hasFileLocalType);
    }

    // Roslyn symbol names omit the source '@', so restore it for keyword identifiers.
    private static string EscapeIdentifier(string value) => SyntaxFacts.GetKeywordKind(value) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(value) != SyntaxKind.None ? $"@{value}" : value;

    private sealed record GenerationInput(EnumSpec Spec, bool IsWrapperPublic, bool IncludeWrapperAttribute, bool IncludeExtensionAttribute);

    private sealed record GenerationPlan(string? Error, ImmutableArray<GenerationInput> Inputs);
}